[package]
name = "smtp-server"
version = "0.1.0"
edition = "2021"


[dependencies]
smtp-proto = { path = "/home/vagrant/code/smtp-proto" }
ahash = { version = "0.8.2" }
rustls = "0.20"
rustls-pemfile = "1.0"
tokio = { version = "1.23.0", features = ["full"] }
tokio-rustls = { version = "0.23.4"}
webpki-roots = { version = "0.22.5"}
parking_lot = "0.12"
